### ISSUE TITLE
Remove Cargo.lock

### ISSUE THREAD

**Issue by androgr** [JMS55/sandbox#24]
# Remove Cargo.lock

I saw that Cargo.lock is also uploaded in the repository, and it's recommended not to hand it over to anybody who's downloading the source code. Cargo likes to generate this file per-build instead, for obvious reasons.

Cargo will regenerate the same file again when the application will be rebuilt, so there isn't a reason for it to exist, apart from giving your build's copy to everybody else.

**Comment by JMS55** [comment]
When you specify `foo = "1.3"` in your `Cargo.toml`, that means "any version of dependency foo 1.3.0 or higher". If `Cargo.lock` is not present, then cargo will choose the latest version available, and set that in `Cargo.lock`. If `Cargo.lock` is present, then cargo will choose exactly the version listed in there, regardless of what the newest compatible version available actually is.

That's the whole point of the `Cargo.lock` file - to explicitly pin your dependencies to specific versions, so that the build can be more reproducible. Generally, applications track their `Cargo.lock` with git; only libraries do not.

See https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html for more info.

**Comment by androgr** [comment]
You learn something new every day I guess :)
